require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-performance

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "node_modules/**/*"
    - "lib/**/*"

  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Lint/MissingSuper:
  AllowedParentClasses:
    - ViewComponent::Base
