services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
      - chrome
    stdin_open: true
    tty: true
    restart: always
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always

  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - '4448:4444'
  
volumes:
  bundle:
  postgres_volume:
