version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f /lean_up/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/lean_up:cached
      - bundle:/usr/local/bundle
    ports:
      - '3006:3000'
    depends_on:
      - db
      - chrome
      - redis
      - sidekiq
    stdin_open: true
    tty: true
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
      REDIS_URL: redis://redis:6379

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always

  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - '4448:4444'

  sidekiq:
    build: .
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/lean_up:cached
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - redis
    command: bundle exec sidekiq

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  bundle:
  postgres_volume:
  redis:
