AWSTemplateFormatVersion: "2010-09-09"
Description: Create task to execute psql command

Parameters:
  SystemName:
    Description: System Name
    Type: String
    Default: leanup
  Environment:
    Description: Environment
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - stg
      - dev
  ResourceName:
    Description: Resource Name
    Type: String
    Default: viacdn

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - SystemName
          - Environment
          - ResourceName

Resources:
  PsqlExecTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: psql-exec-task
      RequiresCompatibilities:
        - EC2
      NetworkMode: bridge
      ExecutionRoleArn: !ImportValue iam-role-AmazonECSTaskExecutionRoleArn
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: psql
          Image: postgres:15
          EntryPoint: ["sh", "-c"]
          Command: ["sleep 3600"] # 後で run-task のときに上書きする
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue: !Sub ${SystemName}-${Environment}-${ResourceName}-ecs-service-LogsLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: psql
