service: leanup-sls-toggle-rds

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.11
  stage: prod
  region: ${opt:region, 'ap-northeast-1'}
  deploymentBucket:
    blockPublicAccess: true
  memorySize: 128
  logRetentionInDays: 14
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rds:DescribeDBClusters
            - rds:StartDBCluster
            - rds:StopDBCluster
          Resource: '*' 

functions:
  start-db-cluster:
    handler: handler.start_db_cluster
    events:
      - schedule:
          description: Start all DB Clusters at 05:00(JST) everyday.
          rate: 'cron(0 20 * * ? *)'
  stop-db-cluster:
    handler: handler.stop_db_cluster
    events:
      - schedule:
          description: Stop all DB Clusters at 22:00(JST) everyday.
          rate: 'cron(0 13 * * ? *)'
