development:
  push_line_job:
    class: PushLineJob
    args: []
    schedule: 45 19 * * * Asia/Tokyo

production:
  push_line_job:
    class: PushLineJob
    args: []
    schedule: 0 8 * * * Asia/Tokyo

