name: Security Review

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - uses: anthropics/claude-code-security-review@c19afa74097b892109a6598b94297280ce7d1beb
        with:
          comment-pr: true
          claude-api-key: ${{ secrets.CLAUDE_API_KEY }}


